services:

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
  
  pricing:
    build:
      context: .
      dockerfile: pricing_service/Dockerfile
    container_name: pricing_service
    restart: always
    ports:
      - "50051:50051"
  
  dispatch:
    build:
      context: .
      dockerfile: dispatch_service/Dockerfile
    container_name: dispatch_service
    restart: always
    ports: 
      - "8000:8000"
    depends_on:
      - db
      - pricing
    environment:
      DATABASE_URL: ${DATABASE_URL}
      PRICING_HOST: ${PRICING_HOST}

  prometheus:
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    depends_on:
      - dispatch

  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  db_data:
  grafana_data: