# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: pricing.proto
# Protobuf Python Version: 7.35.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    7,
    35,
    1,
    '',
    'pricing.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpricing.proto\"\x84\x01\n\x0cPriceRequest\x12\x12\n\npickup_lat\x18\x01 \x01(\x02\x12\x13\n\x0bpickup_long\x18\x02 \x01(\x02\x12\x17\n\x0f\x64\x65stination_lat\x18\x03 \x01(\x02\x12\x18\n\x10\x64\x65stination_long\x18\x04 \x01(\x02\x12\x18\n\x10surge_multiplier\x18\x05 \x01(\x01\"0\n\rPriceResponse\x12\r\n\x05price\x18\x01 \x01(\x01\x12\x10\n\x08\x64istance\x18\x02 \x01(\x01\x32;\n\x0ePricingService\x12)\n\x08GetPrice\x12\r.PriceRequest\x1a\x0e.PriceResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pricing_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_PRICEREQUEST']._serialized_start=18
  _globals['_PRICEREQUEST']._serialized_end=150
  _globals['_PRICERESPONSE']._serialized_start=152
  _globals['_PRICERESPONSE']._serialized_end=200
  _globals['_PRICINGSERVICE']._serialized_start=202
  _globals['_PRICINGSERVICE']._serialized_end=261
# @@protoc_insertion_point(module_scope)
